### ISSUE TITLE
[TASK] Admin Edit/Add User bug Fixes 

### ISSUE THREAD

**Issue by ppatel9703** [SEMOSS/semoss-ui#284]
### Description 

When adding and editing new users from admin member setting the following issues need to be fixed

- Form Validation reason needs to in red font 
- check if phone numbers are required 
- when editing the email, editUser required the parameter passed in to be newEmail not email. 

### Existing

Is there any relevant code or ui feature that the developer should know about when resolving this issue. 

### Reference

This issue references. . .
<img width="1320" alt="Screenshot 2024-09-16 at 2 10 24 PM" src="https://github.com/user-attachments/assets/a6bb3e7f-3b9b-41a9-b477-97b6128dde15">

### Tasks

What are more specific tasks that a developer needs to take to consider this issue resolved.

**Comment by ppatel9703** [comment]
@johbaxter  Matt Freshwaters is going to work on this
he wants to know if the phone is required when adding/editing a user

**Comment by johbaxter** [comment]
@mattfreshwaters and @ppatel9703 - I do not think it is required off my head.  Please take a look at our logic for register, it should match to that exact logic.  We can also look at the validation we have on the BE for this.  Take a look at the API route, do we require it on Edit and Add, if so lets just match that logic on BE

**Comment by mattfreshwaters** [comment]
@ppatel9703 @johbaxter This is wrapping up - quick question because I noticed what I thought were 2 smaller bugs during this, not sure if I should go ahead and create new tickets for them? Or if we want to add on here. Primarily:
- When clicking edit on a user, I don't see the email field being populated from the original value (not sure if that is intended)
- The regex to detect a phone number thinks the following is valid ('123-456-') it stops checking after the second hyphen, so this regex should be updated to detect for a full 10 digit phone number.

**Comment by ppatel9703** [comment]
@mattfreshwaters @johbaxter Matt if you have time, go ahead and address those two issues as well. I'll update to the ticket to include those two bugs (not sure if you have access to) 
If you don't have time we can make a new ticket and sign it off during sprint review.

**Comment by mattfreshwaters** [comment]
@ppatel9703 Sounds good! Need to nail down to things for MDE today but I'll get cracking on it asap

**Comment by johbaxter** [comment]
@mattfreshwaters please put estimated completion data.  Just for planning on my side with code review

**Comment by mattfreshwaters** [comment]
@johbaxter Lets say this Friday Sept 27th - client work permitting, will update if that seems unrealistic later on in the week
