### ISSUE TITLE
[DES] Brainstorm UX for split screen

### ISSUE THREAD

**Issue by natdink** [SEMOSS/semoss-ui#313]
Leadership would really like a split screen between design and data to ease the friction between having to toggle between the distinct pages. 

Considerations in the update:
- pipeline/graph view will be a future feature which will be available in the app builder and when turned on will replace data and design
- design is on left side so that it is closest to the drag and drop menu
- block settings were on far right when design was a single page; decision is to nest settings after block selection and provide multiple interaction points for user to bring up when needed (double click on element to get block settings, click out of element tor return to blocks panel)
- design page should mirror notebook and have sheets which will represent pages
- possibly moving app title to put the action button front and center and not to close to the back button

**Comment by natdink** [comment]
Figma: https://www.figma.com/design/Qj4tWPsniFOJ6qSLfxOaBT/UI-Builder---Design?node-id=6718-5537&t=filw9DnHmFPnJIyp-1

**Comment by natdink** [comment]
Reviewed with Neel notes:

- consider current interaction confusion of button in canvas
- possibly do a close button on left menu instead of back
- combine viz and blocks into one for now 
- how to handle the future scenario of many types of cells in the future (possibly 1:1 with options in legacy pipeline)

**Comment by johbaxter** [comment]
Notes from call with PK, Kunal, Maher, Neel Natalie, John: 
 
**Updates to split screen approach:**

- [x] Update the dropdown menu so that its checkboxes: notebook, design, settings
- [x] Add close option for tabs
- [x] If you close one then they have to go back to the dropdown checkbox menu to add it back
- [x] Ability to Minimize and maximize panels
- [x] Fix the left side menu so that its not draggable with golden layout
- [x] Do the vertical approach for the menu options
- [x] Add File explorer to menu
- [x] Update alpha/beta statement to be less invasive, rethink placement or make it transparent
- [x] Menu can be icons instead of text or text and icons
- [x] Move Download to Settings
- [x] Keep Share button
- [x] Remove Launch
- [ ] Update buttons to icons with hover text and keyboard control hints
- [ ] Update Preview to Present to match legacy SEMOSS 
- [ ] Put API Order into Settings
 
**Notebook**

- [ ] Padding in the code section
- [ ] Wants a minimum height on the output 
- [ ] Likes Output white - we already have this - not sure what ask is??
- [ ] Likes the bounding box on cell -we already have this - not sure what ask is??

**Comment by neelneelneel** [comment]
Replaced with flex-layout
